import 'package:flutter/material.dart';

import 'data/message_repository.dart';
import 'data/profile_repository.dart';
import 'domain/chat_message.dart';
import 'domain/demo_profile.dart';
import 'domain/discovery_preferences.dart';
import 'domain/match_connection.dart';
import 'domain/safety_report.dart';
import 'domain/user_profile.dart';
import 'features/discovery/discovery_deck.dart';
import 'features/matches/match_tabs.dart';

void main() => runApp(const EmberApp());

class EmberApp extends StatelessWidget {
  const EmberApp({super.key});
  @override
  Widget build(BuildContext context) => MaterialApp(
    debugShowCheckedModeBanner: false,
    title: 'Project Ember',
    theme: ThemeData(
      colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFFE84A72)),
      scaffoldBackgroundColor: const Color(0xFFFFF9FA),
      useMaterial3: true,
    ),
    home: const WelcomeScreen(),
  );
}

class WelcomeScreen extends StatefulWidget {
  const WelcomeScreen({super.key});
  @override
  State<WelcomeScreen> createState() => _WelcomeScreenState();
}

class _WelcomeScreenState extends State<WelcomeScreen> {
  bool isAdult = false;
  bool acceptsRules = false;

  @override
  Widget build(BuildContext context) => Scaffold(
    body: SafeArea(
      child: Center(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(24),
          child: ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: 520),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                const Icon(
                  Icons.local_fire_department_rounded,
                  size: 64,
                  color: Color(0xFFE84A72),
                ),
                const SizedBox(height: 20),
                Text(
                  'Meet with intention.',
                  textAlign: TextAlign.center,
                  style: Theme.of(context).textTheme.headlineMedium
                      ?.copyWith(fontWeight: FontWeight.w800),
                ),
                const SizedBox(height: 12),
                const Text(
                  'Project Ember is a private, safety-first place to meet. This early prototype uses synthetic profiles only.',
                  textAlign: TextAlign.center,
                ),
                const SizedBox(height: 28),
                Card(
                  child: Padding(
                    padding: const EdgeInsets.all(12),
                    child: Column(
                      children: [
                        CheckboxListTile(
                          key: const Key('adult-checkbox'),
                          value: isAdult,
                          onChanged: (value) =>
                              setState(() => isAdult = value ?? false),
                          title: const Text('I am at least 18 years old'),
                          subtitle: const Text(
                            'Age assurance will be required before public launch.',
                          ),
                          controlAffinity: ListTileControlAffinity.leading,
                        ),
                        CheckboxListTile(
                          key: const Key('rules-checkbox'),
                          value: acceptsRules,
                          onChanged: (value) =>
                              setState(() => acceptsRules = value ?? false),
                          title: const Text(
                            'I agree to treat people with respect',
                          ),
                          subtitle: const Text(
                            'No harassment, hate, impersonation, scams, or sexual content without consent.',
                          ),
                          controlAffinity: ListTileControlAffinity.leading,
                        ),
                      ],
                    ),
                  ),
                ),
                const SizedBox(height: 20),
                FilledButton(
                  key: const Key('continue-button'),
                  onPressed: isAdult && acceptsRules
                      ? () => Navigator.of(context).pushReplacement(
                          MaterialPageRoute<void>(
                            builder: (_) => const DiscoveryScreen(),
                          ),
                        )
                      : null,
                  child: const Padding(
                    padding: EdgeInsets.symmetric(vertical: 14),
                    child: Text('Continue'),
                  ),
                ),
                const SizedBox(height: 12),
                const Text(
                  'Continuing will not create an account or upload data in this prototype.',
                  textAlign: TextAlign.center,
                  style: TextStyle(fontSize: 12),
                ),
              ],
            ),
          ),
        ),
      ),
    ),
  );
}

class DiscoveryScreen extends StatefulWidget {
  const DiscoveryScreen({super.key});
  @override
  State<DiscoveryScreen> createState() => _DiscoveryScreenState();
}

class _DiscoveryScreenState extends State<DiscoveryScreen> {
  int selectedIndex = 0;
  int profileIndex = 0;
  DiscoveryPreferences discoveryPreferences = const DiscoveryPreferences();
  final blockedProfileAssets = <String>{};
  final discoveryReports = <String, DiscoveryProfileReport>{};
  final ProfileRepository profileRepository = MemoryProfileRepository();
  final MemoryMessageRepository messageRepository = MemoryMessageRepository();
  UserProfile? userProfile;
  SafetyReport? safetyReport;
  MatchConnection connection = const MatchConnection(
    matchId: 'synthetic-match-1',
    peerName: 'Maya',
    peerCallReady: true,
  );

  @override
  void initState() {
    super.initState();
    messageRepository.seed(connection.matchId, [
      ChatMessage(
        id: 'seed-peer',
        author: MessageAuthor.peer,
        text: 'Hi! What is your ideal Sunday?',
        sentAt: DateTime.utc(2026, 9, 20, 12),
      ),
      ChatMessage(
        id: 'seed-user',
        author: MessageAuthor.currentUser,
        text: 'Coffee, a long walk, and cooking something new.',
        sentAt: DateTime.utc(2026, 9, 20, 12, 1),
      ),
    ]);
  }

  static const profiles = [
    DemoProfile(
      'Maya',
      29,
      'Long-term relationship',
      '2–5 km away',
      'Sunday markets, tiny concerts, and ambitious pasta experiments.',
      ['Kindness', 'Live music', 'Cooking'],
      'assets/profiles/maya.png',
    ),
    DemoProfile(
      'Elena',
      32,
      'Long-term relationship',
      '5–10 km away',
      'Bookshop regular, neighborhood explorer, and enthusiastic brunch host.',
      ['Books', 'Cooking', 'Arts'],
      'assets/profiles/elena.png',
    ),
    DemoProfile(
      'Amina',
      27,
      'Open to long-term',
      '2–5 km away',
      'Plant lover, weekend cyclist, and always looking for a new gallery.',
      ['Outdoors', 'Fitness', 'Arts'],
      'assets/profiles/amina.png',
    ),
    DemoProfile(
      'Sofia',
      35,
      'Long-term relationship',
      '10–20 km away',
      'Farmers markets, live jazz, and dinners that run pleasantly late.',
      ['Music', 'Cooking', 'Travel'],
      'assets/profiles/sofia.png',
    ),
    DemoProfile(
      'Mei',
      30,
      'Open to long-term',
      '5–10 km away',
      'Museum afternoons, design books, and finding the best noodles in town.',
      ['Arts', 'Books', 'Travel'],
      'assets/profiles/mei.png',
    ),
    DemoProfile(
      'Nadia',
      33,
      'Long-term relationship',
      '5–10 km away',
      'Riverside walks, contemporary fiction, and finding the perfect flatbread.',
      ['Books', 'Outdoors', 'Cooking'],
      'assets/profiles/nadia.png',
    ),
    DemoProfile(
      'Grace',
      28,
      'Open to long-term',
      '2–5 km away',
      'Early bakery runs, dance classes, and hosting game nights.',
      ['Cooking', 'Fitness', 'Music'],
      'assets/profiles/grace.png',
    ),
    DemoProfile(
      'Valentina',
      31,
      'Long-term relationship',
      '10–20 km away',
      'Garden weekends, live theater, and making travel plans over coffee.',
      ['Outdoors', 'Arts', 'Travel'],
      'assets/profiles/valentina.png',
    ),
    DemoProfile(
      'Leila',
      36,
      'Open to long-term',
      '5–10 km away',
      'Gallery openings, architecture walks, and slow Sunday breakfasts.',
      ['Arts', 'Books', 'Cooking'],
      'assets/profiles/leila.png',
    ),
    DemoProfile(
      'Chloe',
      26,
      'Long-term relationship',
      '2–5 km away',
      'Lakeside picnics, indie films, and learning new recipes.',
      ['Outdoors', 'Arts', 'Cooking'],
      'assets/profiles/chloe.png',
    ),
    DemoProfile(
      'Camila',
      34,
      'Long-term relationship',
      '5–10 km away',
      'City gardens, weekend dancing, and sharing ambitious home cooking.',
      ['Outdoors', 'Music', 'Cooking'],
      'assets/profiles/camila.png',
    ),
    DemoProfile(
      'Derya',
      29,
      'Open to long-term',
      '2–5 km away',
      'Waterfront walks, live comedy, and a carefully curated reading list.',
      ['Books', 'Arts', 'Outdoors'],
      'assets/profiles/derya.png',
    ),
    DemoProfile(
      'Thuy',
      37,
      'Long-term relationship',
      '10–20 km away',
      'Libraries, quiet courtyards, and planning trips around great food.',
      ['Books', 'Travel', 'Cooking'],
      'assets/profiles/thuy.png',
    ),
    DemoProfile(
      'Selam',
      31,
      'Open to long-term',
      '5–10 km away',
      'Botanical walks, dance workouts, and trying every café nearby.',
      ['Outdoors', 'Fitness', 'Cooking'],
      'assets/profiles/selam.png',
    ),
    DemoProfile(
      'Amelie',
      27,
      'Long-term relationship',
      '2–5 km away',
      'Flower markets, sketchbooks, and films with excellent soundtracks.',
      ['Arts', 'Music', 'Travel'],
      'assets/profiles/amelie.png',
    ),
    DemoProfile(
      'Zuri',
      32,
      'Long-term relationship',
      '5–10 km away',
      'Community gardens, morning runs, and cooking for friends.',
      ['Outdoors', 'Fitness', 'Cooking'],
      'assets/profiles/zuri.png',
    ),
    DemoProfile(
      'Ines',
      35,
      'Open to long-term',
      '10–20 km away',
      'City overlooks, pottery classes, and slow weekend breakfasts.',
      ['Arts', 'Travel', 'Cooking'],
      'assets/profiles/ines.png',
    ),
    DemoProfile(
      'Yara',
      28,
      'Long-term relationship',
      '2–5 km away',
      'Courtyard cafés, contemporary novels, and live acoustic sets.',
      ['Books', 'Music', 'Arts'],
      'assets/profiles/yara.png',
    ),
    DemoProfile(
      'Sari',
      30,
      'Open to long-term',
      '5–10 km away',
      'Riverside cycling, design markets, and finding excellent noodles.',
      ['Fitness', 'Arts', 'Cooking'],
      'assets/profiles/sari.png',
    ),
    DemoProfile(
      'Anya',
      38,
      'Long-term relationship',
      '10–20 km away',
      'Outdoor book stalls, classical concerts, and winter walks.',
      ['Books', 'Music', 'Outdoors'],
      'assets/profiles/anya.png',
    ),
    DemoProfile(
      'Aisha',
      34,
      'Long-term relationship',
      '5–10 km away',
      'Tropical gardens, craft workshops, and long weekend lunches.',
      ['Outdoors', 'Arts', 'Cooking'],
      'assets/profiles/aisha.png',
    ),
    DemoProfile(
      'Lucia',
      29,
      'Open to long-term',
      '2–5 km away',
      'Waterfront sunsets, salsa nights, and neighborhood food finds.',
      ['Music', 'Fitness', 'Cooking'],
      'assets/profiles/lucia.png',
    ),
    DemoProfile(
      'Kasia',
      36,
      'Long-term relationship',
      '10–20 km away',
      'Autumn walks, mystery novels, and learning new recipes.',
      ['Outdoors', 'Books', 'Cooking'],
      'assets/profiles/kasia.png',
    ),
    DemoProfile(
      'Hodan',
      31,
      'Open to long-term',
      '5–10 km away',
      'Botanical courtyards, thoughtful conversation, and museum weekends.',
      ['Outdoors', 'Books', 'Arts'],
      'assets/profiles/hodan.png',
    ),
    DemoProfile(
      'Mariam',
      38,
      'Long-term relationship',
      '10–20 km away',
      'Golden-hour walks, family recipes, and independent films.',
      ['Outdoors', 'Cooking', 'Arts'],
      'assets/profiles/mariam.png',
    ),
    DemoProfile(
      'Noura',
      33,
      'Long-term relationship',
      '5–10 km away',
      'Coastal gardens, jazz evenings, and shared meals.',
      ['Outdoors', 'Music', 'Cooking'],
      'assets/profiles/noura.png',
    ),
    DemoProfile(
      'Elise',
      28,
      'Open to long-term',
      '2–5 km away',
      'Sculpture parks, cycling, and quiet Sunday cafés.',
      ['Arts', 'Fitness', 'Books'],
      'assets/profiles/elise.png',
    ),
    DemoProfile(
      'Adwoa',
      36,
      'Long-term relationship',
      '10–20 km away',
      'Garden walks, live music, and dinner with friends.',
      ['Outdoors', 'Music', 'Cooking'],
      'assets/profiles/adwoa.png',
    ),
    DemoProfile(
      'Rina',
      30,
      'Open to long-term',
      '5–10 km away',
      'Waterfront walks, design exhibits, and weekend travel.',
      ['Outdoors', 'Arts', 'Travel'],
      'assets/profiles/rina.png',
    ),
    DemoProfile(
      'Milena',
      39,
      'Long-term relationship',
      '10–20 km away',
      'Riverside evenings, novels, and ambitious baking.',
      ['Outdoors', 'Books', 'Cooking'],
      'assets/profiles/milena.png',
    ),
    DemoProfile(
      'Samira',
      32,
      'Long-term relationship',
      '5–10 km away',
      'Garden walks, music, and shared dinners.',
      ['Outdoors', 'Music', 'Cooking'],
      'assets/profiles/samira.png',
    ),
    DemoProfile(
      'Maeve',
      37,
      'Open to long-term',
      '10–20 km away',
      'Coastal paths, novels, and live shows.',
      ['Outdoors', 'Books', 'Music'],
      'assets/profiles/maeve.png',
    ),
    DemoProfile(
      'Lindiwe',
      29,
      'Long-term relationship',
      '2–5 km away',
      'Botanical walks, dance, and weekend cooking.',
      ['Outdoors', 'Fitness', 'Cooking'],
      'assets/profiles/lindiwe.png',
    ),
    DemoProfile(
      'Petra',
      35,
      'Open to long-term',
      '5–10 km away',
      'Marina evenings, photography, and travel.',
      ['Outdoors', 'Arts', 'Travel'],
      'assets/profiles/petra.png',
    ),
    DemoProfile(
      'Noor',
      30,
      'Long-term relationship',
      '10–20 km away',
      'Courtyard cafés, books, and museum days.',
      ['Books', 'Arts', 'Cooking'],
      'assets/profiles/noor.png',
    ),
    DemoProfile(
      'Nino',
      34,
      'Long-term relationship',
      '5–10 km away',
      'Hillside gardens, architecture, and long dinners.',
      ['Outdoors', 'Arts', 'Cooking'],
      'assets/profiles/nino.png',
    ),
    DemoProfile(
      'Marisol',
      29,
      'Open to long-term',
      '2–5 km away',
      'Botanical walks, dancing, and weekend markets.',
      ['Outdoors', 'Fitness', 'Cooking'],
      'assets/profiles/marisol.png',
    ),
    DemoProfile(
      'Keza',
      37,
      'Long-term relationship',
      '10–20 km away',
      'Lakeside walks, books, and live jazz.',
      ['Outdoors', 'Books', 'Music'],
      'assets/profiles/keza.png',
    ),
    DemoProfile(
      'Aino',
      31,
      'Open to long-term',
      '5–10 km away',
      'Harbor gardens, design, and hiking weekends.',
      ['Outdoors', 'Arts', 'Travel'],
      'assets/profiles/aino.png',
    ),
    DemoProfile(
      'Rima',
      35,
      'Long-term relationship',
      '10–20 km away',
      'Stone courtyards, museums, and shared recipes.',
      ['Outdoors', 'Arts', 'Cooking'],
      'assets/profiles/rima.png',
    ),
    DemoProfile(
      'Oksana',
      33,
      'Long-term relationship',
      '5–10 km away',
      'Courtyard gardens, architecture, and weekend baking.',
      ['Outdoors', 'Arts', 'Cooking'],
      'assets/profiles/oksana.png',
    ),
    DemoProfile(
      'Isidora',
      30,
      'Open to long-term',
      '2–5 km away',
      'Botanical walks, dancing, and independent films.',
      ['Outdoors', 'Fitness', 'Arts'],
      'assets/profiles/isidora.png',
    ),
    DemoProfile(
      'Abena',
      36,
      'Long-term relationship',
      '10–20 km away',
      'Garden afternoons, live music, and dinner with friends.',
      ['Outdoors', 'Music', 'Cooking'],
      'assets/profiles/abena.png',
    ),
    DemoProfile(
      'Freyja',
      28,
      'Open to long-term',
      '5–10 km away',
      'Waterfront walks, design books, and quiet road trips.',
      ['Outdoors', 'Books', 'Travel'],
      'assets/profiles/freyja.png',
    ),
    DemoProfile(
      'Dalia',
      38,
      'Long-term relationship',
      '10–20 km away',
      'Stone courtyards, family recipes, and museum weekends.',
      ['Outdoors', 'Cooking', 'Arts'],
      'assets/profiles/dalia.png',
    ),
    DemoProfile(
      'Irina',
      32,
      'Long-term relationship',
      '5–10 km away',
      'Old-town walks, architecture, and relaxed dinner parties.',
      ['Outdoors', 'Arts', 'Cooking'],
      'assets/profiles/elena_ro.png',
    ),
    DemoProfile(
      'Awa',
      37,
      'Open to long-term',
      '10–20 km away',
      'Riverside gardens, live music, and Sunday reading.',
      ['Outdoors', 'Music', 'Books'],
      'assets/profiles/awa.png',
    ),
    DemoProfile(
      'Anahit',
      29,
      'Long-term relationship',
      '2–5 km away',
      'Mountain views, museums, and trying new recipes.',
      ['Outdoors', 'Arts', 'Cooking'],
      'assets/profiles/anahit.png',
    ),
    DemoProfile(
      'Simone',
      35,
      'Open to long-term',
      '5–10 km away',
      'Coastal gardens, dancing, and spontaneous road trips.',
      ['Outdoors', 'Fitness', 'Travel'],
      'assets/profiles/simone.png',
    ),
    DemoProfile(
      'Margot',
      31,
      'Long-term relationship',
      '10–20 km away',
      'Canal walks, design books, and intimate concerts.',
      ['Outdoors', 'Books', 'Music'],
      'assets/profiles/elise_be.png',
    ),
    DemoProfile(
      'Kavya',
      28,
      'Open to long-term',
      '2–5 km away',
      'Campus gardens, indie films, and experimental cooking.',
      ['Outdoors', 'Arts', 'Cooking'],
      'assets/profiles/ind_kavya.png',
      'Indian',
    ),
    DemoProfile(
      'Meera',
      34,
      'Long-term relationship',
      '5–10 km away',
      'Waterfront walks, novels, and hosting relaxed dinners.',
      ['Outdoors', 'Books', 'Cooking'],
      'assets/profiles/ind_meera.png',
      'Indian',
    ),
    DemoProfile(
      'Zoya',
      31,
      'Open to long-term',
      '10–20 km away',
      'Gallery courtyards, live music, and weekend travel.',
      ['Arts', 'Music', 'Travel'],
      'assets/profiles/ind_zoya.png',
      'Indian',
    ),
    DemoProfile(
      'Nandini',
      37,
      'Long-term relationship',
      '5–10 km away',
      'Botanical afternoons, architecture, and family recipes.',
      ['Outdoors', 'Arts', 'Cooking'],
      'assets/profiles/ind_nandini.png',
      'Indian',
    ),
    DemoProfile(
      'Rhea',
      29,
      'Open to long-term',
      '2–5 km away',
      'City parks, morning runs, and spontaneous road trips.',
      ['Outdoors', 'Fitness', 'Travel'],
      'assets/profiles/ind_rhea.png',
      'Indian',
    ),
    DemoProfile(
      'Tara',
      30,
      'Long-term relationship',
      '5–10 km away',
      'Library gardens, book clubs, and relaxed neighborhood dinners.',
      ['Outdoors', 'Books', 'Cooking'],
      'assets/profiles/ind_tara.png',
      'Indian',
    ),
    DemoProfile(
      'Isha',
      36,
      'Open to long-term',
      '10–20 km away',
      'Riverside evenings, live music, and photography walks.',
      ['Outdoors', 'Music', 'Arts'],
      'assets/profiles/ind_isha.png',
      'Indian',
    ),
    DemoProfile(
      'Priya',
      27,
      'Long-term relationship',
      '2–5 km away',
      'City plazas, morning runs, and weekend road trips.',
      ['Outdoors', 'Fitness', 'Travel'],
      'assets/profiles/ind_priya.png',
      'Indian',
    ),
    DemoProfile(
      'Leela',
      39,
      'Open to long-term',
      '5–10 km away',
      'Heritage gardens, architecture, and cooking for friends.',
      ['Outdoors', 'Arts', 'Cooking'],
      'assets/profiles/ind_leela.png',
      'Indian',
    ),
    DemoProfile(
      'Sana',
      33,
      'Long-term relationship',
      '10–20 km away',
      'Coastal parks, novels, and finding small live venues.',
      ['Outdoors', 'Books', 'Music'],
      'assets/profiles/ind_sana.png',
      'Indian',
    ),
    DemoProfile(
      'Ayesha',
      29,
      'Open to long-term',
      '2–5 km away',
      'University gardens, design podcasts, and weekend baking.',
      ['Outdoors', 'Arts', 'Cooking'],
      'assets/profiles/pak_ayesha.png',
      'Pakistani',
    ),
    DemoProfile(
      'Hira',
      35,
      'Long-term relationship',
      '5–10 km away',
      'Riverside walks, books, and small live shows.',
      ['Outdoors', 'Books', 'Music'],
      'assets/profiles/pak_hira.png',
      'Pakistani',
    ),
    DemoProfile(
      'Mahnoor',
      31,
      'Open to long-term',
      '10–20 km away',
      'Arts courtyards, photography, and spontaneous travel.',
      ['Arts', 'Outdoors', 'Travel'],
      'assets/profiles/pak_mahnoor.png',
      'Pakistani',
    ),
    DemoProfile(
      'Saba',
      38,
      'Long-term relationship',
      '5–10 km away',
      'Botanical afternoons, architecture, and relaxed dinners.',
      ['Outdoors', 'Arts', 'Cooking'],
      'assets/profiles/pak_saba.png',
      'Pakistani',
    ),
    DemoProfile(
      'Alina',
      27,
      'Open to long-term',
      '2–5 km away',
      'City parks, morning runs, and film nights.',
      ['Outdoors', 'Fitness', 'Arts'],
      'assets/profiles/pak_alina.png',
      'Pakistani',
    ),
    DemoProfile(
      'Eman',
      30,
      'Long-term relationship',
      '5–10 km away',
      'Bookshop courtyards, design podcasts, and weekend baking.',
      ['Books', 'Arts', 'Cooking'],
      'assets/profiles/pak_eman.png',
      'Pakistani',
    ),
    DemoProfile(
      'Laiba',
      34,
      'Open to long-term',
      '10–20 km away',
      'Riverside gardens, live music, and relaxed city breaks.',
      ['Outdoors', 'Music', 'Travel'],
      'assets/profiles/pak_laiba.png',
      'Pakistani',
    ),
    DemoProfile(
      'Mehwish',
      39,
      'Long-term relationship',
      '5–10 km away',
      'Arts courtyards, photography, and dinners with friends.',
      ['Arts', 'Outdoors', 'Cooking'],
      'assets/profiles/pak_mehwish.png',
      'Pakistani',
    ),
    DemoProfile(
      'Rabia',
      28,
      'Open to long-term',
      '2–5 km away',
      'Botanical walks, morning fitness, and independent films.',
      ['Outdoors', 'Fitness', 'Arts'],
      'assets/profiles/pak_rabia.png',
      'Pakistani',
    ),
    DemoProfile(
      'Sidra',
      36,
      'Long-term relationship',
      '10–20 km away',
      'Museum gardens, thoughtful books, and long weekend drives.',
      ['Arts', 'Books', 'Travel'],
      'assets/profiles/pak_sidra.png',
      'Pakistani',
    ),
    DemoProfile(
      'Tasnim',
      29,
      'Open to long-term',
      '2–5 km away',
      'Botanical courtyards, design books, and weekend baking.',
      ['Outdoors', 'Books', 'Cooking'],
      'assets/profiles/bd_tasnim.png',
      'Bangladeshi',
    ),
    DemoProfile(
      'Nusrat',
      35,
      'Long-term relationship',
      '5–10 km away',
      'Riverside evenings, live music, and relaxed city walks.',
      ['Outdoors', 'Music', 'Travel'],
      'assets/profiles/bd_nusrat.png',
      'Bangladeshi',
    ),
    DemoProfile(
      'Farzana',
      40,
      'Open to long-term',
      '10–20 km away',
      'Arts gardens, photography, and cooking for friends.',
      ['Arts', 'Outdoors', 'Cooking'],
      'assets/profiles/bd_farzana.png',
      'Bangladeshi',
    ),
    DemoProfile(
      'Jannat',
      27,
      'Long-term relationship',
      '2–5 km away',
      'Cycling paths, morning workouts, and independent films.',
      ['Outdoors', 'Fitness', 'Arts'],
      'assets/profiles/bd_jannat.png',
      'Bangladeshi',
    ),
    DemoProfile(
      'Rukhsana',
      33,
      'Open to long-term',
      '5–10 km away',
      'Museum courtyards, thoughtful novels, and road trips.',
      ['Arts', 'Books', 'Travel'],
      'assets/profiles/bd_rukhsana.png',
      'Bangladeshi',
    ),
    DemoProfile(
      'Sharmin',
      31,
      'Long-term relationship',
      '5–10 km away',
      'Library gardens, thoughtful books, and neighborhood dinners.',
      ['Outdoors', 'Books', 'Cooking'],
      'assets/profiles/bd_sharmin.png',
      'Bangladeshi',
    ),
    DemoProfile(
      'Mitu',
      28,
      'Open to long-term',
      '2–5 km away',
      'Riverside parks, live shows, and spontaneous city breaks.',
      ['Outdoors', 'Music', 'Travel'],
      'assets/profiles/bd_mitu.png',
      'Bangladeshi',
    ),
    DemoProfile(
      'Tanjila',
      37,
      'Long-term relationship',
      '10–20 km away',
      'Architecture walks, photography, and relaxed cooking.',
      ['Arts', 'Outdoors', 'Cooking'],
      'assets/profiles/bd_tanjila.png',
      'Bangladeshi',
    ),
    DemoProfile(
      'Lamis',
      34,
      'Open to long-term',
      '5–10 km away',
      'Lakeside art, morning fitness, and independent films.',
      ['Arts', 'Fitness', 'Outdoors'],
      'assets/profiles/bd_lamis.png',
      'Bangladeshi',
    ),
    DemoProfile(
      'Nabila',
      41,
      'Long-term relationship',
      '10–20 km away',
      'Botanical terraces, novels, and long weekend drives.',
      ['Outdoors', 'Books', 'Travel'],
      'assets/profiles/bd_nabila.png',
      'Bangladeshi',
    ),
    DemoProfile(
      'Yuxin',
      28,
      'Open to long-term',
      '2â€“5 km away',
      'Bookshop afternoons, urban sketching, and trying new noodle spots.',
      ['Books', 'Arts', 'Cooking'],
      'assets/profiles/cn_yuxin.png',
      'Chinese',
    ),
    DemoProfile(
      'Wenqi',
      34,
      'Long-term relationship',
      '5â€“10 km away',
      'Riverside cycling, live jazz, and carefully planned weekend trips.',
      ['Fitness', 'Music', 'Travel'],
      'assets/profiles/cn_wenqi.png',
      'Chinese',
    ),
    DemoProfile(
      'Xinyi',
      31,
      'Open to long-term',
      '10â€“20 km away',
      'Contemporary galleries, botanical walks, and dinner parties with friends.',
      ['Arts', 'Outdoors', 'Cooking'],
      'assets/profiles/cn_xinyi.png',
      'Chinese',
    ),
    DemoProfile(
      'Jia',
      37,
      'Long-term relationship',
      '5â€“10 km away',
      'Architecture podcasts, literary fiction, and quiet coastal escapes.',
      ['Arts', 'Books', 'Travel'],
      'assets/profiles/cn_jia.png',
      'Chinese',
    ),
    DemoProfile(
      'Ruolan',
      29,
      'Open to long-term',
      '2â€“5 km away',
      'Morning runs, independent films, and finding intimate concert venues.',
      ['Fitness', 'Arts', 'Music'],
      'assets/profiles/cn_ruolan.png',
      'Chinese',
    ),
    DemoProfile(
      'Lihua',
      33,
      'Long-term relationship',
      '5â€“10 km away',
      'Library courtyards, literary fiction, and home cooking.',
      ['Books', 'Arts', 'Cooking'],
      'assets/profiles/cn_lihua.png',
      'Chinese',
    ),
    DemoProfile(
      'Mengyao',
      28,
      'Open to long-term',
      '2â€“5 km away',
      'Riverside cycling, live shows, and weekend city breaks.',
      ['Fitness', 'Music', 'Travel'],
      'assets/profiles/cn_mengyao.png',
      'Chinese',
    ),
    DemoProfile(
      'Qian',
      39,
      'Long-term relationship',
      '10â€“20 km away',
      'Sculpture gardens, architecture, and dinners with friends.',
      ['Arts', 'Outdoors', 'Cooking'],
      'assets/profiles/cn_qian.png',
      'Chinese',
    ),
    DemoProfile(
      'Shanshan',
      31,
      'Open to long-term',
      '5â€“10 km away',
      'Flower markets, photography, and independent films.',
      ['Outdoors', 'Arts', 'Books'],
      'assets/profiles/cn_shanshan.png',
      'Chinese',
    ),
    DemoProfile(
      'Xiaoyu',
      36,
      'Long-term relationship',
      '10â€“20 km away',
      'Coastal hikes, travel writing, and acoustic music.',
      ['Outdoors', 'Travel', 'Music'],
      'assets/profiles/cn_xiaoyu.png',
      'Chinese',
    ),
    DemoProfile(
      'Aiko',
      30,
      'Open to long-term',
      '2â€“5 km away',
      'Botanical afternoons, design books, and relaxed home cooking.',
      ['Outdoors', 'Books', 'Cooking'],
      'assets/profiles/jp_aiko.png',
      'Japanese',
    ),
    DemoProfile(
      'Emi',
      36,
      'Long-term relationship',
      '5â€“10 km away',
      'Waterfront walks, live jazz, and carefully planned getaways.',
      ['Outdoors', 'Music', 'Travel'],
      'assets/profiles/jp_emi.png',
      'Japanese',
    ),
    DemoProfile(
      'Nanami',
      27,
      'Open to long-term',
      '2â€“5 km away',
      'Ceramics studios, independent films, and neighborhood cafes.',
      ['Arts', 'Books', 'Cooking'],
      'assets/profiles/jp_nanami.png',
      'Japanese',
    ),
    DemoProfile(
      'Sayaka',
      40,
      'Long-term relationship',
      '10â€“20 km away',
      'Sculpture gardens, architecture, and long weekend drives.',
      ['Arts', 'Outdoors', 'Travel'],
      'assets/profiles/jp_sayaka.png',
      'Japanese',
    ),
    DemoProfile(
      'Yui',
      33,
      'Open to long-term',
      '5â€“10 km away',
      'Cycling paths, photography walks, and intimate concerts.',
      ['Fitness', 'Arts', 'Music'],
      'assets/profiles/jp_yui.png',
      'Japanese',
    ),
    DemoProfile(
      'Akari',
      29,
      'Open to long-term',
      '2â€“5 km away',
      'Rose gardens, illustration books, and weekend baking.',
      ['Outdoors', 'Arts', 'Cooking'],
      'assets/profiles/jp_akari.png',
      'Japanese',
    ),
    DemoProfile(
      'Chihiro',
      35,
      'Long-term relationship',
      '5â€“10 km away',
      'Canal walks, thoughtful novels, and live acoustic sets.',
      ['Outdoors', 'Books', 'Music'],
      'assets/profiles/jp_chihiro.png',
      'Japanese',
    ),
    DemoProfile(
      'Kaori',
      41,
      'Open to long-term',
      '10â€“20 km away',
      'Modern architecture, photography, and relaxed city breaks.',
      ['Arts', 'Outdoors', 'Travel'],
      'assets/profiles/jp_kaori.png',
      'Japanese',
    ),
    DemoProfile(
      'Misaki',
      32,
      'Long-term relationship',
      '5â€“10 km away',
      'Coastal trails, morning fitness, and independent cinema.',
      ['Outdoors', 'Fitness', 'Arts'],
      'assets/profiles/jp_misaki.png',
      'Japanese',
    ),
    DemoProfile(
      'Tomomi',
      38,
      'Open to long-term',
      '10â€“20 km away',
      'Library gardens, home cooking, and long weekend drives.',
      ['Books', 'Cooking', 'Travel'],
      'assets/profiles/jp_tomomi.png',
      'Japanese',
    ),
    DemoProfile(
      'Althea',
      28,
      'Open to long-term',
      '2â€“5 km away',
      'Campus gardens, illustration, and trying new recipes.',
      ['Outdoors', 'Arts', 'Cooking'],
      'assets/profiles/ph_althea.png',
      'Filipino',
    ),
    DemoProfile(
      'Bianca',
      34,
      'Long-term relationship',
      '5â€“10 km away',
      'Waterfront walks, live music, and weekend escapes.',
      ['Outdoors', 'Music', 'Travel'],
      'assets/profiles/ph_bianca.png',
      'Filipino',
    ),
    DemoProfile(
      'Camille',
      31,
      'Open to long-term',
      '10â€“20 km away',
      'Arts centers, photography, and relaxed dinner parties.',
      ['Arts', 'Outdoors', 'Cooking'],
      'assets/profiles/ph_camille.png',
      'Filipino',
    ),
    DemoProfile(
      'Denise',
      39,
      'Long-term relationship',
      '5â€“10 km away',
      'Botanical afternoons, literary fiction, and acoustic shows.',
      ['Outdoors', 'Books', 'Music'],
      'assets/profiles/ph_denise.png',
      'Filipino',
    ),
    DemoProfile(
      'Mariel',
      36,
      'Open to long-term',
      '10â€“20 km away',
      'Coastal paths, morning fitness, and spontaneous road trips.',
      ['Outdoors', 'Fitness', 'Travel'],
      'assets/profiles/ph_mariel.png',
      'Filipino',
    ),
    DemoProfile(
      'Bea',
      26,
      'Open to long-term',
      '2â€“5 km away',
      'Riverside cycling, graphic novels, and weekend food hunts.',
      ['Fitness', 'Books', 'Cooking'],
      'assets/profiles/ph_bea.png',
      'Filipino',
    ),
    DemoProfile(
      'Celeste',
      43,
      'Long-term relationship',
      '10â€“20 km away',
      'Library courtyards, architecture, and intimate jazz sets.',
      ['Books', 'Arts', 'Music'],
      'assets/profiles/ph_celeste.png',
      'Filipino',
    ),
    DemoProfile(
      'Inez',
      32,
      'Open to long-term',
      '5â€“10 km away',
      'Community gardens, photography, and cooking for friends.',
      ['Outdoors', 'Arts', 'Cooking'],
      'assets/profiles/ph_inez.png',
      'Filipino',
    ),
    DemoProfile(
      'Katrina',
      38,
      'Long-term relationship',
      '10â€“20 km away',
      'Coastal hikes, morning training, and spontaneous travel.',
      ['Outdoors', 'Fitness', 'Travel'],
      'assets/profiles/ph_katrina.png',
      'Filipino',
    ),
    DemoProfile(
      'Liza',
      47,
      'Open to long-term',
      '5â€“10 km away',
      'Sculpture parks, literary memoirs, and relaxed dinners.',
      ['Arts', 'Books', 'Cooking'],
      'assets/profiles/ph_liza.png',
      'Filipino',
    ),
    DemoProfile(
      'Jisoo',
      27,
      'Open to long-term',
      '2â€“5 km away',
      'Riverside walks, illustration, and weekend baking.',
      ['Outdoors', 'Arts', 'Cooking'],
      'assets/profiles/kr_jisoo.png',
      'Korean',
    ),
    DemoProfile(
      'Minji',
      35,
      'Long-term relationship',
      '5â€“10 km away',
      'Library gardens, literary fiction, and intimate concerts.',
      ['Books', 'Outdoors', 'Music'],
      'assets/profiles/kr_minji.png',
      'Korean',
    ),
    DemoProfile(
      'Sora',
      42,
      'Open to long-term',
      '10â€“20 km away',
      'Sculpture courtyards, architecture, and relaxed travel.',
      ['Arts', 'Outdoors', 'Travel'],
      'assets/profiles/kr_sora.png',
      'Korean',
    ),
    DemoProfile(
      'Yuna',
      31,
      'Long-term relationship',
      '5â€“10 km away',
      'Coastal trails, morning fitness, and photography walks.',
      ['Outdoors', 'Fitness', 'Arts'],
      'assets/profiles/kr_yuna.png',
      'Korean',
    ),
    DemoProfile(
      'Hyejin',
      38,
      'Open to long-term',
      '10â€“20 km away',
      'Botanical afternoons, thoughtful books, and dinner parties.',
      ['Outdoors', 'Books', 'Cooking'],
      'assets/profiles/kr_hyejin.png',
      'Korean',
    ),
    DemoProfile(
      'Eunchae',
      26,
      'Open to long-term',
      '2–5 km away',
      'Ceramics workshops, tiny galleries, and experimental baking.',
      ['Arts', 'Cooking', 'Outdoors'],
      'assets/profiles/kr_eunchae.png',
      'Korean',
    ),
    DemoProfile(
      'Dabin',
      34,
      'Long-term relationship',
      '5–10 km away',
      'Community gardens, trail runs, and cooking from scratch.',
      ['Outdoors', 'Fitness', 'Cooking'],
      'assets/profiles/kr_dabin.png',
      'Korean',
    ),
    DemoProfile(
      'Nari',
      41,
      'Open to long-term',
      '10–20 km away',
      'Architecture walks, essay collections, and quiet city breaks.',
      ['Arts', 'Books', 'Travel'],
      'assets/profiles/kr_nari.png',
      'Korean',
    ),
    DemoProfile(
      'Seoyeon',
      47,
      'Long-term relationship',
      '20–50 km away',
      'Waterfront mornings, folk playlists, and lively dinner tables.',
      ['Outdoors', 'Music', 'Cooking'],
      'assets/profiles/kr_seoyeon.png',
      'Korean',
    ),
    DemoProfile(
      'Mirae',
      52,
      'Open to long-term',
      '10–20 km away',
      'Botanical sketches, memoirs, and unhurried train journeys.',
      ['Arts', 'Books', 'Travel'],
      'assets/profiles/kr_mirae.png',
      'Korean',
    ),
    DemoProfile(
      'Ximena',
      25,
      'Open to long-term',
      '2–5 km away',
      'Sculpture courtyards, morning runs, and late-night playlists.',
      ['Arts', 'Fitness', 'Music'],
      'assets/profiles/mx_ximena.png',
      'Mexican',
    ),
    DemoProfile(
      'Renata',
      33,
      'Long-term relationship',
      '5–10 km away',
      'Rooftop gardens, design books, and relaxed weekend cooking.',
      ['Outdoors', 'Books', 'Cooking'],
      'assets/profiles/mx_renata.png',
      'Mexican',
    ),
    DemoProfile(
      'Paloma',
      39,
      'Open to long-term',
      '10–20 km away',
      'Lakeside walks, live vocals, and dinner with a full table.',
      ['Outdoors', 'Music', 'Cooking'],
      'assets/profiles/mx_paloma.png',
      'Mexican',
    ),
    DemoProfile(
      'Itzel',
      46,
      'Long-term relationship',
      '20–50 km away',
      'Modern art, architecture trips, and quiet literary essays.',
      ['Arts', 'Travel', 'Books'],
      'assets/profiles/mx_itzel.png',
      'Mexican',
    ),
    DemoProfile(
      'Fernanda',
      53,
      'Open to long-term',
      '10–20 km away',
      'Coastal trails, botanical sketches, and thoughtful memoirs.',
      ['Outdoors', 'Arts', 'Books'],
      'assets/profiles/mx_fernanda.png',
      'Mexican',
    ),
    DemoProfile(
      'Abril',
      29,
      'Long-term relationship',
      '5–10 km away',
      'Library courtyards, illustrated essays, and finding new running routes.',
      ['Books', 'Arts', 'Fitness'],
      'assets/profiles/mx_abril.png',
      'Mexican',
    ),
    DemoProfile(
      'Marisol',
      36,
      'Open to long-term',
      '10–20 km away',
      'Ceramics afternoons, neighborhood gardens, and ambitious weekend meals.',
      ['Arts', 'Outdoors', 'Cooking'],
      'assets/profiles/mx_marisol.png',
      'Mexican',
    ),
    DemoProfile(
      'Nayeli',
      43,
      'Long-term relationship',
      '20–50 km away',
      'Conservatory walks, live jazz, and slow journeys with a good book.',
      ['Outdoors', 'Music', 'Travel'],
      'assets/profiles/mx_nayeli.png',
      'Mexican',
    ),
    DemoProfile(
      'Adriana',
      50,
      'Open to long-term',
      '10–20 km away',
      'Waterfront mornings, modern architecture, and thoughtful memoirs.',
      ['Outdoors', 'Arts', 'Books'],
      'assets/profiles/mx_adriana.png',
      'Mexican',
    ),
    DemoProfile(
      'Teresa',
      59,
      'Long-term relationship',
      '5–10 km away',
      'Community gardens, family recipes, and music that fills the kitchen.',
      ['Outdoors', 'Cooking', 'Music'],
      'assets/profiles/mx_teresa.png',
      'Mexican',
    ),
    DemoProfile(
      'Marcus',
      30,
      'Long-term relationship',
      '2–5 km away',
      'Coffee walks, pickup basketball, and cooking for friends.',
      ['Fitness', 'Cooking', 'Music'],
      'assets/profiles/marcus.png',
    ),
    DemoProfile(
      'Daniel',
      34,
      'Open to long-term',
      '5–10 km away',
      'Record collector, amateur photographer, and reliable road-trip DJ.',
      ['Music', 'Arts', 'Travel'],
      'assets/profiles/daniel.png',
    ),
    DemoProfile(
      'Arjun',
      29,
      'Long-term relationship',
      '10–20 km away',
      'Runner, home cook, and the person who reads every museum label.',
      ['Fitness', 'Cooking', 'Arts'],
      'assets/profiles/arjun.png',
    ),
    DemoProfile(
      'Ethan',
      36,
      'Open to long-term',
      '5–10 km away',
      'Community gardener, history reader, and beginner bread baker.',
      ['Outdoors', 'Books', 'Cooking'],
      'assets/profiles/ethan.png',
    ),
    DemoProfile(
      'Minjun',
      31,
      'Long-term relationship',
      '2–5 km away',
      'City walks, independent films, and planning the next hiking weekend.',
      ['Arts', 'Outdoors', 'Travel'],
      'assets/profiles/minjun.png',
    ),
    DemoProfile(
      'Jamal',
      32,
      'Long-term relationship',
      '5–10 km away',
      'Botanical gardens, jazz playlists, and cooking with friends.',
      ['Outdoors', 'Music', 'Cooking'],
      'assets/profiles/jamal.png',
    ),
    DemoProfile(
      'Luca',
      35,
      'Open to long-term',
      '10–20 km away',
      'Old-town cafés, cycling, and an unreasonable number of cookbooks.',
      ['Fitness', 'Books', 'Cooking'],
      'assets/profiles/luca.png',
    ),
    DemoProfile(
      'Tomas',
      28,
      'Long-term relationship',
      '2–5 km away',
      'Weekend football, street photography, and hunting down great tacos.',
      ['Fitness', 'Arts', 'Cooking'],
      'assets/profiles/tomas.png',
    ),
    DemoProfile(
      'Andre',
      37,
      'Open to long-term',
      '5–10 km away',
      'Waterfront runs, soul records, and planning relaxed dinner parties.',
      ['Fitness', 'Music', 'Cooking'],
      'assets/profiles/andre.png',
    ),
    DemoProfile(
      'Noah',
      30,
      'Long-term relationship',
      '10–20 km away',
      'Mountain trails, small-town cafés, and documentary nights.',
      ['Outdoors', 'Travel', 'Arts'],
      'assets/profiles/noah.png',
    ),
    DemoProfile(
      'Kwame',
      33,
      'Long-term relationship',
      '5–10 km away',
      'Public gardens, live percussion, and cooking for a full table.',
      ['Outdoors', 'Music', 'Cooking'],
      'assets/profiles/kwame.png',
    ),
    DemoProfile(
      'Ronan',
      36,
      'Open to long-term',
      '10–20 km away',
      'Coastal hikes, history podcasts, and finding welcoming pubs.',
      ['Outdoors', 'Books', 'Travel'],
      'assets/profiles/ronan.png',
    ),
    DemoProfile(
      'Omar',
      30,
      'Long-term relationship',
      '2–5 km away',
      'Museum afternoons, pickup football, and perfecting breakfast.',
      ['Arts', 'Fitness', 'Cooking'],
      'assets/profiles/omar.png',
    ),
    DemoProfile(
      'Niran',
      28,
      'Open to long-term',
      '5–10 km away',
      'Rainy park walks, street food, and a growing vinyl collection.',
      ['Outdoors', 'Cooking', 'Music'],
      'assets/profiles/niran.png',
    ),
    DemoProfile(
      'Nikos',
      38,
      'Long-term relationship',
      '10–20 km away',
      'Marina evenings, architecture, and hosting relaxed Sunday lunches.',
      ['Travel', 'Arts', 'Cooking'],
      'assets/profiles/nikos.png',
    ),
    DemoProfile(
      'Mateo',
      31,
      'Long-term relationship',
      '2–5 km away',
      'Colorful neighborhoods, weekend football, and sunset photography.',
      ['Arts', 'Fitness', 'Travel'],
      'assets/profiles/mateo.png',
    ),
    DemoProfile(
      'Emmanuel',
      35,
      'Open to long-term',
      '5–10 km away',
      'Public gardens, contemporary art, and elaborate Sunday dinners.',
      ['Outdoors', 'Arts', 'Cooking'],
      'assets/profiles/emmanuel.png',
    ),
    DemoProfile(
      'Tane',
      29,
      'Long-term relationship',
      '10–20 km away',
      'Waterfront trails, social basketball, and discovering new music.',
      ['Outdoors', 'Fitness', 'Music'],
      'assets/profiles/tane.png',
    ),
    DemoProfile(
      'Pavel',
      37,
      'Open to long-term',
      '5–10 km away',
      'Old-town walks, history books, and experimenting with bread.',
      ['Outdoors', 'Books', 'Cooking'],
      'assets/profiles/pavel.png',
    ),
    DemoProfile(
      'Farid',
      33,
      'Long-term relationship',
      '2–5 km away',
      'Botanical gardens, documentary films, and generous dinner tables.',
      ['Outdoors', 'Arts', 'Cooking'],
      'assets/profiles/farid.png',
    ),
    DemoProfile(
      'Daan',
      32,
      'Long-term relationship',
      '5–10 km away',
      'Canal cycling, live music, and experimental home cooking.',
      ['Fitness', 'Music', 'Cooking'],
      'assets/profiles/daan.png',
    ),
    DemoProfile(
      'Idrissa',
      35,
      'Open to long-term',
      '2–5 km away',
      'Art spaces, community events, and a great Sunday playlist.',
      ['Arts', 'Music', 'Outdoors'],
      'assets/profiles/idrissa.png',
    ),
    DemoProfile(
      'Sebastian',
      28,
      'Long-term relationship',
      '10–20 km away',
      'Hilltop hikes, street photography, and late coffee.',
      ['Outdoors', 'Arts', 'Travel'],
      'assets/profiles/sebastian.png',
    ),
    DemoProfile(
      'Andrei',
      37,
      'Open to long-term',
      '5–10 km away',
      'Old-town walks, tennis, and hosting relaxed dinners.',
      ['Outdoors', 'Fitness', 'Cooking'],
      'assets/profiles/andrei.png',
    ),
    DemoProfile(
      'Timur',
      30,
      'Long-term relationship',
      '2–5 km away',
      'Modern gardens, architecture books, and weekend road trips.',
      ['Outdoors', 'Books', 'Travel'],
      'assets/profiles/timur.png',
    ),
    DemoProfile(
      'Youssef',
      34,
      'Long-term relationship',
      '5–10 km away',
      'Courtyard cafés, running, and cooking for friends.',
      ['Outdoors', 'Fitness', 'Cooking'],
      'assets/profiles/youssef.png',
    ),
    DemoProfile(
      'Henrik',
      38,
      'Open to long-term',
      '10–20 km away',
      'Harbor walks, design books, and live concerts.',
      ['Outdoors', 'Books', 'Music'],
      'assets/profiles/henrik.png',
    ),
    DemoProfile(
      'Chinedu',
      31,
      'Long-term relationship',
      '2–5 km away',
      'Botanical trails, basketball, and film nights.',
      ['Outdoors', 'Fitness', 'Arts'],
      'assets/profiles/chinedu.png',
    ),
    DemoProfile(
      'Rafael',
      29,
      'Open to long-term',
      '5–10 km away',
      'City plazas, street photography, and weekend cooking.',
      ['Arts', 'Travel', 'Cooking'],
      'assets/profiles/rafael.png',
    ),
    DemoProfile(
      'Batu',
      35,
      'Long-term relationship',
      '10–20 km away',
      'Public gardens, hiking, and architecture podcasts.',
      ['Outdoors', 'Fitness', 'Books'],
      'assets/profiles/batu.png',
    ),
    DemoProfile(
      'Karim',
      36,
      'Long-term relationship',
      '5–10 km away',
      'Seaside walks, running, and home cooking.',
      ['Outdoors', 'Fitness', 'Cooking'],
      'assets/profiles/karim.png',
    ),
    DemoProfile(
      'Marek',
      33,
      'Open to long-term',
      '10–20 km away',
      'River walks, history, and small concerts.',
      ['Outdoors', 'Books', 'Music'],
      'assets/profiles/marek.png',
    ),
    DemoProfile(
      'Tendai',
      38,
      'Long-term relationship',
      '2–5 km away',
      'City gardens, jazz, and dinner parties.',
      ['Outdoors', 'Music', 'Cooking'],
      'assets/profiles/tendai.png',
    ),
    DemoProfile(
      'Joao',
      28,
      'Open to long-term',
      '5–10 km away',
      'City overlooks, football, and photography.',
      ['Travel', 'Fitness', 'Arts'],
      'assets/profiles/joao.png',
    ),
    DemoProfile(
      'Ari',
      31,
      'Long-term relationship',
      '10–20 km away',
      'Harbor trails, hiking, and film nights.',
      ['Outdoors', 'Travel', 'Arts'],
      'assets/profiles/ari.png',
    ),
    DemoProfile(
      'Diego',
      32,
      'Long-term relationship',
      '5–10 km away',
      'Hilltop walks, football, and photography.',
      ['Outdoors', 'Fitness', 'Arts'],
      'assets/profiles/diego.png',
    ),
    DemoProfile(
      'Dawit',
      38,
      'Open to long-term',
      '10–20 km away',
      'Botanical trails, jazz, and Sunday cooking.',
      ['Outdoors', 'Music', 'Cooking'],
      'assets/profiles/dawit.png',
    ),
    DemoProfile(
      'Lars',
      30,
      'Long-term relationship',
      '2–5 km away',
      'Waterfront hikes, books, and live shows.',
      ['Outdoors', 'Books', 'Music'],
      'assets/profiles/lars.png',
    ),
    DemoProfile(
      'Giorgi',
      36,
      'Open to long-term',
      '5–10 km away',
      'Garden terraces, architecture, and dinner parties.',
      ['Outdoors', 'Arts', 'Cooking'],
      'assets/profiles/giorgi.png',
    ),
    DemoProfile(
      'Sami',
      28,
      'Long-term relationship',
      '10–20 km away',
      'Coastal walks, running, and weekend travel.',
      ['Outdoors', 'Fitness', 'Travel'],
      'assets/profiles/sami.png',
    ),
    DemoProfile(
      'Luka',
      35,
      'Long-term relationship',
      '5–10 km away',
      'Seaside walks, photography, and cooking for friends.',
      ['Outdoors', 'Arts', 'Cooking'],
      'assets/profiles/luka.png',
    ),
    DemoProfile(
      'Nicolas',
      31,
      'Open to long-term',
      '10–20 km away',
      'Hillside trails, live music, and weekend travel.',
      ['Outdoors', 'Music', 'Travel'],
      'assets/profiles/nicolas.png',
    ),
    DemoProfile(
      'Kato',
      39,
      'Long-term relationship',
      '5–10 km away',
      'Lakeside gardens, jazz records, and Sunday brunch.',
      ['Outdoors', 'Music', 'Cooking'],
      'assets/profiles/kato.png',
    ),
    DemoProfile(
      'Mikkel',
      29,
      'Open to long-term',
      '2–5 km away',
      'Waterfront runs, novels, and small concerts.',
      ['Fitness', 'Books', 'Music'],
      'assets/profiles/mikkel.png',
    ),
    DemoProfile(
      'Yacine',
      34,
      'Long-term relationship',
      '10–20 km away',
      'Garden terraces, architecture, and coastal drives.',
      ['Outdoors', 'Arts', 'Travel'],
      'assets/profiles/yacine.png',
    ),
    DemoProfile(
      'Stefan',
      36,
      'Long-term relationship',
      '5–10 km away',
      'Riverside walks, photography, and cooking for friends.',
      ['Outdoors', 'Arts', 'Cooking'],
      'assets/profiles/stefan.png',
    ),
    DemoProfile(
      'Andres',
      30,
      'Open to long-term',
      '2–5 km away',
      'Botanical trails, live shows, and weekend travel.',
      ['Outdoors', 'Music', 'Travel'],
      'assets/profiles/andres.png',
    ),
    DemoProfile(
      'Alain',
      38,
      'Long-term relationship',
      '10–20 km away',
      'Garden afternoons, jazz, and ambitious home cooking.',
      ['Outdoors', 'Music', 'Cooking'],
      'assets/profiles/alain.png',
    ),
    DemoProfile(
      'Cian',
      28,
      'Open to long-term',
      '5–10 km away',
      'Coastal hikes, novels, and small live venues.',
      ['Outdoors', 'Books', 'Music'],
      'assets/profiles/cian.png',
    ),
    DemoProfile(
      'Zaid',
      34,
      'Long-term relationship',
      '10–20 km away',
      'Courtyard gardens, architecture, and long weekend drives.',
      ['Outdoors', 'Arts', 'Travel'],
      'assets/profiles/omar_jo.png',
    ),
    DemoProfile(
      'Vihaan',
      32,
      'Long-term relationship',
      '5–10 km away',
      'Tree-lined walks, photography, and Sunday cooking.',
      ['Outdoors', 'Arts', 'Cooking'],
      'assets/profiles/ind_vihaan.png',
      'Indian',
    ),
    DemoProfile(
      'Kabir',
      36,
      'Open to long-term',
      '10–20 km away',
      'Lakeside paths, jazz playlists, and history books.',
      ['Outdoors', 'Music', 'Books'],
      'assets/profiles/ind_kabir.png',
      'Indian',
    ),
    DemoProfile(
      'Rohan',
      29,
      'Long-term relationship',
      '2–5 km away',
      'Garden runs, live shows, and weekend getaways.',
      ['Fitness', 'Music', 'Travel'],
      'assets/profiles/ind_rohan.png',
      'Indian',
    ),
    DemoProfile(
      'Dev',
      38,
      'Open to long-term',
      '5–10 km away',
      'Stone courtyards, architecture, and ambitious dinners.',
      ['Outdoors', 'Arts', 'Cooking'],
      'assets/profiles/ind_dev.png',
      'Indian',
    ),
    DemoProfile(
      'Imran',
      33,
      'Long-term relationship',
      '10–20 km away',
      'Riverside evenings, books, and planning the next trip.',
      ['Outdoors', 'Books', 'Travel'],
      'assets/profiles/ind_imran.png',
      'Indian',
    ),
    DemoProfile(
      'Neel',
      31,
      'Open to long-term',
      '2–5 km away',
      'Museum gardens, design, and Sunday brunch experiments.',
      ['Outdoors', 'Arts', 'Cooking'],
      'assets/profiles/ind_neel.png',
      'Indian',
    ),
    DemoProfile(
      'Aditya',
      35,
      'Long-term relationship',
      '5–10 km away',
      'Leafy trails, history books, and acoustic shows.',
      ['Outdoors', 'Books', 'Music'],
      'assets/profiles/ind_aditya.png',
      'Indian',
    ),
    DemoProfile(
      'Sameer',
      28,
      'Open to long-term',
      '10–20 km away',
      'Waterfront walks, fitness, and spontaneous travel.',
      ['Outdoors', 'Fitness', 'Travel'],
      'assets/profiles/ind_sameer.png',
      'Indian',
    ),
    DemoProfile(
      'Kunal',
      40,
      'Long-term relationship',
      '5–10 km away',
      'Botanical terraces, jazz, and hosting dinner nights.',
      ['Outdoors', 'Music', 'Cooking'],
      'assets/profiles/ind_kunal.png',
      'Indian',
    ),
    DemoProfile(
      'Aarav',
      34,
      'Open to long-term',
      '2–5 km away',
      'Arts campuses, architecture, and long weekend drives.',
      ['Outdoors', 'Arts', 'Travel'],
      'assets/profiles/ind_aarav.png',
      'Indian',
    ),
    DemoProfile(
      'Hamza',
      32,
      'Long-term relationship',
      '5–10 km away',
      'Tree-lined walks, photography, and cooking for friends.',
      ['Outdoors', 'Arts', 'Cooking'],
      'assets/profiles/pak_hamza.png',
      'Pakistani',
    ),
    DemoProfile(
      'Bilal',
      37,
      'Open to long-term',
      '10–20 km away',
      'Lakeside paths, history books, and jazz.',
      ['Outdoors', 'Books', 'Music'],
      'assets/profiles/pak_bilal.png',
      'Pakistani',
    ),
    DemoProfile(
      'Usman',
      29,
      'Long-term relationship',
      '2–5 km away',
      'Garden runs, live shows, and weekend travel.',
      ['Fitness', 'Music', 'Travel'],
      'assets/profiles/pak_usman.png',
      'Pakistani',
    ),
    DemoProfile(
      'Farhan',
      40,
      'Open to long-term',
      '5–10 km away',
      'Courtyard architecture, novels, and Sunday cooking.',
      ['Arts', 'Books', 'Cooking'],
      'assets/profiles/pak_farhan.png',
      'Pakistani',
    ),
    DemoProfile(
      'Daniyal',
      34,
      'Long-term relationship',
      '10–20 km away',
      'Waterfront evenings, music, and long road trips.',
      ['Outdoors', 'Music', 'Travel'],
      'assets/profiles/pak_daniyal.png',
      'Pakistani',
    ),
    DemoProfile(
      'Shahzaib',
      31,
      'Open to long-term',
      '2–5 km away',
      'University walks, pickup games, and neighborhood cafés.',
      ['Outdoors', 'Fitness', 'Cooking'],
      'assets/profiles/pak_shahzaib.png',
      'Pakistani',
    ),
    DemoProfile(
      'Fahad',
      36,
      'Long-term relationship',
      '5–10 km away',
      'Cultural centers, history books, and acoustic shows.',
      ['Arts', 'Books', 'Music'],
      'assets/profiles/pak_fahad.png',
      'Pakistani',
    ),
    DemoProfile(
      'Waleed',
      28,
      'Open to long-term',
      '2–5 km away',
      'City-park runs, photography, and spontaneous travel.',
      ['Fitness', 'Arts', 'Travel'],
      'assets/profiles/pak_waleed.png',
      'Pakistani',
    ),
    DemoProfile(
      'Noman',
      41,
      'Long-term relationship',
      '10–20 km away',
      'Heritage gardens, ambitious cooking, and jazz evenings.',
      ['Outdoors', 'Cooking', 'Music'],
      'assets/profiles/pak_noman.png',
      'Pakistani',
    ),
    DemoProfile(
      'Saad',
      33,
      'Open to long-term',
      '5–10 km away',
      'Waterfront walks, design, and relaxed road trips.',
      ['Outdoors', 'Arts', 'Travel'],
      'assets/profiles/pak_saad.png',
      'Pakistani',
    ),
    DemoProfile(
      'Tanvir',
      31,
      'Long-term relationship',
      '2–5 km away',
      'University walks, photography, and neighborhood cafés.',
      ['Outdoors', 'Arts', 'Cooking'],
      'assets/profiles/bd_tanvir.png',
      'Bangladeshi',
    ),
    DemoProfile(
      'Shakib',
      37,
      'Open to long-term',
      '5–10 km away',
      'Riverside routes, history books, and live jazz.',
      ['Outdoors', 'Books', 'Music'],
      'assets/profiles/bd_shakib.png',
      'Bangladeshi',
    ),
    DemoProfile(
      'Mahmud',
      42,
      'Long-term relationship',
      '10–20 km away',
      'Arts courtyards, ambitious dinners, and weekend travel.',
      ['Arts', 'Cooking', 'Travel'],
      'assets/profiles/bd_mahmud.png',
      'Bangladeshi',
    ),
    DemoProfile(
      'Rafi',
      28,
      'Open to long-term',
      '2–5 km away',
      'Lakeside runs, design, and spontaneous road trips.',
      ['Fitness', 'Arts', 'Travel'],
      'assets/profiles/bd_rafi.png',
      'Bangladeshi',
    ),
    DemoProfile(
      'Zayed',
      34,
      'Long-term relationship',
      '5–10 km away',
      'Waterfront evenings, cooking, and small live venues.',
      ['Outdoors', 'Cooking', 'Music'],
      'assets/profiles/bd_zayed.png',
      'Bangladeshi',
    ),
    DemoProfile(
      'Arif',
      30,
      'Open to long-term',
      '2–5 km away',
      'Library walks, photography, and cooking for friends.',
      ['Books', 'Arts', 'Cooking'],
      'assets/profiles/bd_arif.png',
      'Bangladeshi',
    ),
    DemoProfile(
      'Faisal',
      38,
      'Long-term relationship',
      '5–10 km away',
      'Riverfront evenings, history books, and live music.',
      ['Outdoors', 'Books', 'Music'],
      'assets/profiles/bd_faisal.png',
      'Bangladeshi',
    ),
    DemoProfile(
      'Rezaul',
      43,
      'Open to long-term',
      '10–20 km away',
      'Sculpture gardens, ambitious dinners, and road trips.',
      ['Arts', 'Cooking', 'Travel'],
      'assets/profiles/bd_rezaul.png',
      'Bangladeshi',
    ),
    DemoProfile(
      'Imtiaz',
      32,
      'Long-term relationship',
      '2–5 km away',
      'Cycling routes, design, and weekend travel.',
      ['Fitness', 'Arts', 'Travel'],
      'assets/profiles/bd_imtiaz.png',
      'Bangladeshi',
    ),
    DemoProfile(
      'Sohan',
      27,
      'Open to long-term',
      '5–10 km away',
      'Waterfront walks, home cooking, and small live venues.',
      ['Outdoors', 'Cooking', 'Music'],
      'assets/profiles/bd_sohan.png',
      'Bangladeshi',
    ),
    DemoProfile(
      'Haoran',
      32,
      'Long-term relationship',
      '5â€“10 km away',
      'Park runs, street photography, and cooking ambitious Sunday lunches.',
      ['Fitness', 'Arts', 'Cooking'],
      'assets/profiles/cn_haoran.png',
      'Chinese',
    ),
    DemoProfile(
      'Junjie',
      38,
      'Open to long-term',
      '10â€“20 km away',
      'History books, small music venues, and train trips to new cities.',
      ['Books', 'Music', 'Travel'],
      'assets/profiles/cn_junjie.png',
      'Chinese',
    ),
    DemoProfile(
      'Wei',
      27,
      'Long-term relationship',
      '2â€“5 km away',
      'Bouldering sessions, design exhibitions, and exploring neighborhood cafes.',
      ['Fitness', 'Arts', 'Cooking'],
      'assets/profiles/cn_wei.png',
      'Chinese',
    ),
    DemoProfile(
      'Zhen',
      35,
      'Open to long-term',
      '5â€“10 km away',
      'Lakeside walks, jazz records, and long-form science writing.',
      ['Outdoors', 'Music', 'Books'],
      'assets/profiles/cn_zhen.png',
      'Chinese',
    ),
    DemoProfile(
      'Bo',
      41,
      'Long-term relationship',
      '10â€“20 km away',
      'Sculpture gardens, regional cooking, and relaxed road trips.',
      ['Arts', 'Cooking', 'Travel'],
      'assets/profiles/cn_bo.png',
      'Chinese',
    ),
    DemoProfile(
      'Cheng',
      30,
      'Open to long-term',
      '2â€“5 km away',
      'Campus walks, pickup games, and neighborhood cafes.',
      ['Outdoors', 'Fitness', 'Cooking'],
      'assets/profiles/cn_cheng.png',
      'Chinese',
    ),
    DemoProfile(
      'Ming',
      37,
      'Long-term relationship',
      '5â€“10 km away',
      'Canal walks, history books, and live jazz.',
      ['Outdoors', 'Books', 'Music'],
      'assets/profiles/cn_ming.png',
      'Chinese',
    ),
    DemoProfile(
      'Tao',
      29,
      'Open to long-term',
      '2â€“5 km away',
      'Design exhibitions, photography, and spontaneous trips.',
      ['Arts', 'Fitness', 'Travel'],
      'assets/profiles/cn_tao.png',
      'Chinese',
    ),
    DemoProfile(
      'Yichen',
      41,
      'Long-term relationship',
      '10â€“20 km away',
      'Botanical paths, ambitious cooking, and thoughtful novels.',
      ['Outdoors', 'Cooking', 'Books'],
      'assets/profiles/cn_yichen.png',
      'Chinese',
    ),
    DemoProfile(
      'Liang',
      34,
      'Open to long-term',
      '5â€“10 km away',
      'Waterfront evenings, live music, and weekend road trips.',
      ['Outdoors', 'Music', 'Travel'],
      'assets/profiles/cn_liang.png',
      'Chinese',
    ),
    DemoProfile(
      'Daichi',
      31,
      'Long-term relationship',
      '2â€“5 km away',
      'Campus gardens, pickup games, and Sunday cooking.',
      ['Outdoors', 'Fitness', 'Cooking'],
      'assets/profiles/jp_daichi.png',
      'Japanese',
    ),
    DemoProfile(
      'Haruto',
      38,
      'Open to long-term',
      '10â€“20 km away',
      'Harbor walks, history books, and small live venues.',
      ['Outdoors', 'Books', 'Music'],
      'assets/profiles/jp_haruto.png',
      'Japanese',
    ),
    DemoProfile(
      'Kenta',
      29,
      'Long-term relationship',
      '5â€“10 km away',
      'Design museums, street photography, and spontaneous travel.',
      ['Arts', 'Fitness', 'Travel'],
      'assets/profiles/jp_kenta.png',
      'Japanese',
    ),
    DemoProfile(
      'Ren',
      42,
      'Open to long-term',
      '10â€“20 km away',
      'Woodland gardens, thoughtful novels, and ambitious dinners.',
      ['Outdoors', 'Books', 'Cooking'],
      'assets/profiles/jp_ren.png',
      'Japanese',
    ),
    DemoProfile(
      'Sota',
      35,
      'Long-term relationship',
      '5â€“10 km away',
      'Riverside evenings, acoustic shows, and weekend road trips.',
      ['Outdoors', 'Music', 'Travel'],
      'assets/profiles/jp_sota.png',
      'Japanese',
    ),
    DemoProfile(
      'Hiroshi',
      39,
      'Long-term relationship',
      '10â€“20 km away',
      'Sculpture courtyards, jazz records, and history books.',
      ['Arts', 'Music', 'Books'],
      'assets/profiles/jp_hiroshi.png',
      'Japanese',
    ),
    DemoProfile(
      'Koji',
      33,
      'Open to long-term',
      '5â€“10 km away',
      'Canal cycling, photography, and cooking for friends.',
      ['Fitness', 'Arts', 'Cooking'],
      'assets/profiles/jp_koji.png',
      'Japanese',
    ),
    DemoProfile(
      'Masato',
      44,
      'Long-term relationship',
      '10â€“20 km away',
      'Botanical afternoons, literary essays, and quiet travel.',
      ['Outdoors', 'Books', 'Travel'],
      'assets/profiles/jp_masato.png',
      'Japanese',
    ),
    DemoProfile(
      'Naoki',
      28,
      'Open to long-term',
      '2â€“5 km away',
      'Cycling routes, live shows, and spontaneous road trips.',
      ['Fitness', 'Music', 'Travel'],
      'assets/profiles/jp_naoki.png',
      'Japanese',
    ),
    DemoProfile(
      'Takumi',
      36,
      'Long-term relationship',
      '5â€“10 km away',
      'Performing arts, architecture walks, and ambitious dinners.',
      ['Arts', 'Outdoors', 'Cooking'],
      'assets/profiles/jp_takumi.png',
      'Japanese',
    ),
    DemoProfile(
      'Enzo',
      30,
      'Long-term relationship',
      '2â€“5 km away',
      'Tree-lined walks, pickup games, and cooking for friends.',
      ['Outdoors', 'Fitness', 'Cooking'],
      'assets/profiles/ph_enzo.png',
      'Filipino',
    ),
    DemoProfile(
      'Gabriel',
      37,
      'Open to long-term',
      '5â€“10 km away',
      'Riverside evenings, history books, and live jazz.',
      ['Outdoors', 'Books', 'Music'],
      'assets/profiles/ph_gabriel.png',
      'Filipino',
    ),
    DemoProfile(
      'Joaquin',
      33,
      'Long-term relationship',
      '10â€“20 km away',
      'Design museums, street photography, and weekend travel.',
      ['Arts', 'Fitness', 'Travel'],
      'assets/profiles/ph_joaquin.png',
      'Filipino',
    ),
    DemoProfile(
      'Luis',
      42,
      'Open to long-term',
      '5â€“10 km away',
      'Tropical gardens, ambitious dinners, and thoughtful novels.',
      ['Outdoors', 'Cooking', 'Books'],
      'assets/profiles/ph_luis.png',
      'Filipino',
    ),
    DemoProfile(
      'Paolo',
      29,
      'Long-term relationship',
      '2â€“5 km away',
      'Harbor walks, small concerts, and spontaneous city breaks.',
      ['Outdoors', 'Music', 'Travel'],
      'assets/profiles/ph_paolo.png',
      'Filipino',
    ),
    DemoProfile(
      'Adrian',
      27,
      'Open to long-term',
      '2â€“5 km away',
      'Skate parks, live music, and budget weekend adventures.',
      ['Fitness', 'Music', 'Travel'],
      'assets/profiles/ph_adrian.png',
      'Filipino',
    ),
    DemoProfile(
      'Carlo',
      35,
      'Long-term relationship',
      '5â€“10 km away',
      'Market courtyards, ambitious cooking, and history podcasts.',
      ['Outdoors', 'Cooking', 'Books'],
      'assets/profiles/ph_carlo.png',
      'Filipino',
    ),
    DemoProfile(
      'Dante',
      46,
      'Open to long-term',
      '10â€“20 km away',
      'Conservatory walks, sculpture, and long road trips.',
      ['Outdoors', 'Arts', 'Travel'],
      'assets/profiles/ph_dante.png',
      'Filipino',
    ),
    DemoProfile(
      'Miguel',
      31,
      'Long-term relationship',
      '5â€“10 km away',
      'Library terraces, design books, and acoustic concerts.',
      ['Books', 'Arts', 'Music'],
      'assets/profiles/ph_miguel.png',
      'Filipino',
    ),
    DemoProfile(
      'Ramon',
      40,
      'Open to long-term',
      '10â€“20 km away',
      'Harbor walks, strength training, and dinner experiments.',
      ['Outdoors', 'Fitness', 'Cooking'],
      'assets/profiles/ph_ramon.png',
      'Filipino',
    ),
    DemoProfile(
      'Jihoon',
      29,
      'Open to long-term',
      '2â€“5 km away',
      'Arts plazas, live shows, and spontaneous city breaks.',
      ['Arts', 'Music', 'Travel'],
      'assets/profiles/kr_jihoon.png',
      'Korean',
    ),
    DemoProfile(
      'Minho',
      36,
      'Long-term relationship',
      '5â€“10 km away',
      'Market courtyards, ambitious cooking, and history books.',
      ['Outdoors', 'Cooking', 'Books'],
      'assets/profiles/kr_minho.png',
      'Korean',
    ),
    DemoProfile(
      'Seojun',
      44,
      'Open to long-term',
      '10â€“20 km away',
      'Conservatory walks, sculpture, and long road trips.',
      ['Outdoors', 'Arts', 'Travel'],
      'assets/profiles/kr_seojun.png',
      'Korean',
    ),
    DemoProfile(
      'Taeyang',
      32,
      'Long-term relationship',
      '5â€“10 km away',
      'Library terraces, design podcasts, and acoustic music.',
      ['Books', 'Arts', 'Music'],
      'assets/profiles/kr_taeyang.png',
      'Korean',
    ),
    DemoProfile(
      'Hyunwoo',
      40,
      'Open to long-term',
      '10â€“20 km away',
      'Harbor walks, strength training, and Sunday cooking.',
      ['Outdoors', 'Fitness', 'Cooking'],
      'assets/profiles/kr_hyunwoo.png',
      'Korean',
    ),
    DemoProfile(
      'Donghyun',
      28,
      'Open to long-term',
      '2–5 km away',
      'Climbing sessions, live sets, and finding the best dumplings.',
      ['Fitness', 'Music', 'Cooking'],
      'assets/profiles/kr_donghyun.png',
      'Korean',
    ),
    DemoProfile(
      'Kyungmin',
      35,
      'Long-term relationship',
      '5–10 km away',
      'Independent bookshops, jazz records, and slow weekend travel.',
      ['Books', 'Music', 'Travel'],
      'assets/profiles/kr_kyungmin.png',
      'Korean',
    ),
    DemoProfile(
      'Jaeho',
      43,
      'Open to long-term',
      '10–20 km away',
      'Lakeside rides, strength work, and ambitious home cooking.',
      ['Outdoors', 'Fitness', 'Cooking'],
      'assets/profiles/kr_jaeho.png',
      'Korean',
    ),
    DemoProfile(
      'Sungmin',
      49,
      'Long-term relationship',
      '20–50 km away',
      'Public art, old soul albums, and spontaneous road trips.',
      ['Arts', 'Music', 'Travel'],
      'assets/profiles/kr_sungmin.png',
      'Korean',
    ),
    DemoProfile(
      'Woobin',
      55,
      'Open to long-term',
      '10–20 km away',
      'Coastal walks, history books, and patient landscape sketches.',
      ['Outdoors', 'Books', 'Arts'],
      'assets/profiles/kr_woobin.png',
      'Korean',
    ),
    DemoProfile(
      'Emiliano',
      27,
      'Open to long-term',
      '2–5 km away',
      'Riverside runs, small concerts, and spontaneous city breaks.',
      ['Fitness', 'Music', 'Travel'],
      'assets/profiles/mx_emiliano.png',
      'Mexican',
    ),
    DemoProfile(
      'Gael',
      34,
      'Long-term relationship',
      '5–10 km away',
      'Woodworking projects, strength training, and Sunday cooking.',
      ['Arts', 'Fitness', 'Cooking'],
      'assets/profiles/mx_gael.png',
      'Mexican',
    ),
    DemoProfile(
      'Balam',
      41,
      'Open to long-term',
      '10–20 km away',
      'Greenhouse afternoons, history books, and slow train travel.',
      ['Outdoors', 'Books', 'Travel'],
      'assets/profiles/mx_balam.png',
      'Mexican',
    ),
    DemoProfile(
      'Armando',
      48,
      'Long-term relationship',
      '20–50 km away',
      'Hill walks, old records, and cooking for a lively crowd.',
      ['Outdoors', 'Music', 'Cooking'],
      'assets/profiles/mx_armando.png',
      'Mexican',
    ),
    DemoProfile(
      'Salvador',
      56,
      'Open to long-term',
      '10–20 km away',
      'Library terraces, landscape drawing, and unhurried journeys.',
      ['Books', 'Arts', 'Travel'],
      'assets/profiles/mx_salvador.png',
      'Mexican',
    ),
    DemoProfile(
      'Mauricio',
      31,
      'Long-term relationship',
      '2–5 km away',
      'Courtyard coffee, strength training, and cooking without a recipe.',
      ['Fitness', 'Cooking', 'Music'],
      'assets/profiles/mx_mauricio.png',
      'Mexican',
    ),
    DemoProfile(
      'Hector',
      38,
      'Open to long-term',
      '5–10 km away',
      'Long bike trails, live sets, and planning the next road trip.',
      ['Fitness', 'Music', 'Travel'],
      'assets/profiles/mx_hector.png',
      'Mexican',
    ),
    DemoProfile(
      'Rodrigo',
      45,
      'Long-term relationship',
      '10–20 km away',
      'Museum afternoons, design histories, and unhurried city walks.',
      ['Arts', 'Books', 'Outdoors'],
      'assets/profiles/mx_rodrigo.png',
      'Mexican',
    ),
    DemoProfile(
      'Ignacio',
      52,
      'Open to long-term',
      '20–50 km away',
      'Lakeside walks, patient home cooking, and landscape photography.',
      ['Outdoors', 'Cooking', 'Arts'],
      'assets/profiles/mx_ignacio.png',
      'Mexican',
    ),
    DemoProfile(
      'Cesar',
      60,
      'Long-term relationship',
      '10–20 km away',
      'Park chess, history books, and train journeys with no fixed schedule.',
      ['Books', 'Travel', 'Outdoors'],
      'assets/profiles/mx_cesar.png',
      'Mexican',
    ),
  ];

  @override
  Widget build(BuildContext context) {
    final pages = [
      _discover(context),
      MatchTab(
        connection: connection,
        onOpenChat: () => setState(() => selectedIndex = 2),
      ),
      ChatTab(
        connection: connection,
        messages: messageRepository.list(connection.matchId),
        report: safetyReport,
        onSend: _sendMessage,
        onCallReadinessChanged: (value) => setState(
          () => connection = connection.setCurrentUserCallReady(value),
        ),
        onReport: (report) => setState(() {
          safetyReport = report;
          connection = connection.report();
        }),
        onUnmatch: () => setState(() => connection = connection.unmatch()),
        onBlock: () => setState(() => connection = connection.block()),
      ),
      ProfileEditor(
        initialProfile: userProfile,
        onSaved: (profile) {
          profileRepository.save(profile);
          setState(() => userProfile = profileRepository.load());
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('Profile saved on this device session only.'),
            ),
          );
        },
      ),
    ];
    return Scaffold(
      appBar: AppBar(
        title: const Text(
          'Project Ember',
          style: TextStyle(fontWeight: FontWeight.w800),
        ),
        actions: [
          IconButton(
            tooltip: 'Safety center',
            icon: const Icon(Icons.shield_outlined),
            onPressed: () => showModalBottomSheet<void>(
              context: context,
              showDragHandle: true,
              builder: (_) => const SafetySheet(),
            ),
          ),
        ],
      ),
      body: IndexedStack(index: selectedIndex, children: pages),
      bottomNavigationBar: NavigationBar(
        selectedIndex: selectedIndex,
        onDestinationSelected: (value) => setState(() => selectedIndex = value),
        destinations: const [
          NavigationDestination(
            icon: Icon(Icons.explore_outlined),
            selectedIcon: Icon(Icons.explore),
            label: 'Discover',
          ),
          NavigationDestination(
            icon: Icon(Icons.favorite_outline),
            selectedIcon: Icon(Icons.favorite),
            label: 'Matches',
          ),
          NavigationDestination(
            key: Key('chat-tab'),
            icon: Icon(Icons.chat_bubble_outline),
            selectedIcon: Icon(Icons.chat_bubble),
            label: 'Chats',
          ),
          NavigationDestination(
            key: Key('profile-tab'),
            icon: Icon(Icons.person_outline),
            selectedIcon: Icon(Icons.person),
            label: 'Profile',
          ),
        ],
      ),
    );
  }

  Widget _discover(BuildContext context) => DiscoveryDeck(
    profiles: profiles,
    preferences: discoveryPreferences,
    blockedProfileAssets: blockedProfileAssets,
    reports: discoveryReports,
    profileIndex: profileIndex,
    onPreferencesChanged: (updated) => setState(() {
      discoveryPreferences = updated;
      profileIndex = 0;
    }),
    onNextProfile: _nextProfile,
    onReport: (report) =>
        setState(() => discoveryReports[report.profileAssetPath] = report),
    onBlockProfile: (profile) => setState(() {
      blockedProfileAssets.add(profile.assetPath);
      profileIndex = 0;
    }),
  );
  void _nextProfile() => setState(() => profileIndex += 1);

  void _sendMessage(String text) {
    final result = messageRepository.send(
      matchId: connection.matchId,
      text: text,
      connectionActive: connection.canMessage,
    );
    if (!result.accepted) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text(result.error ?? 'Message was not sent.')),
      );
      return;
    }
    setState(() {});
  }
}

class ProfileEditor extends StatefulWidget {
  const ProfileEditor({
    super.key,
    required this.initialProfile,
    required this.onSaved,
  });

  final UserProfile? initialProfile;
  final ValueChanged<UserProfile> onSaved;

  @override
  State<ProfileEditor> createState() => _ProfileEditorState();
}

class _ProfileEditorState extends State<ProfileEditor> {
  static const availableInterests = [
    'Arts',
    'Books',
    'Cooking',
    'Fitness',
    'Music',
    'Outdoors',
    'Travel',
  ];
  final formKey = GlobalKey<FormState>();
  late final TextEditingController nameController;
  late final TextEditingController ageController;
  late final TextEditingController bioController;
  late RelationshipIntent intent;
  late Set<String> interests;
  late bool showDistanceBand;
  late bool callReadyByDefault;

  @override
  void initState() {
    super.initState();
    final profile = widget.initialProfile;
    nameController = TextEditingController(text: profile?.displayName ?? '');
    ageController = TextEditingController(text: profile?.age.toString() ?? '');
    bioController = TextEditingController(text: profile?.bio ?? '');
    intent = profile?.intent ?? RelationshipIntent.openToLongTerm;
    interests = {...?profile?.interests};
    showDistanceBand = profile?.showDistanceBand ?? true;
    callReadyByDefault = profile?.callReadyByDefault ?? false;
  }

  @override
  void dispose() {
    nameController.dispose();
    ageController.dispose();
    bioController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => Form(
    key: formKey,
    child: SingleChildScrollView(
      key: const Key('profile-scroll'),
      padding: const EdgeInsets.fromLTRB(20, 8, 20, 32),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          Text(
            'Your profile',
            style: Theme.of(context).textTheme.headlineSmall
                ?.copyWith(fontWeight: FontWeight.w800),
          ),
          const SizedBox(height: 6),
          const Text(
            'Prototype data stays in memory and disappears when the app closes.',
          ),
          const SizedBox(height: 20),
          TextFormField(
            key: const Key('profile-name'),
            controller: nameController,
            maxLength: 40,
            textCapitalization: TextCapitalization.words,
            decoration: const InputDecoration(labelText: 'Display name'),
            validator: (value) => UserProfile.validateName(value ?? ''),
          ),
          const SizedBox(height: 12),
          TextFormField(
            key: const Key('profile-age'),
            controller: ageController,
            keyboardType: TextInputType.number,
            decoration: const InputDecoration(labelText: 'Age'),
            validator: (value) => UserProfile.validateAge(value ?? ''),
          ),
          const SizedBox(height: 16),
          DropdownButtonFormField<RelationshipIntent>(
            key: const Key('profile-intent'),
            initialValue: intent,
            decoration: const InputDecoration(
              labelText: 'What are you looking for?',
            ),
            items: RelationshipIntent.values
                .map(
                  (value) =>
                      DropdownMenuItem(value: value, child: Text(value.label)),
                )
                .toList(),
            onChanged: (value) => setState(() => intent = value ?? intent),
          ),
          const SizedBox(height: 16),
          TextFormField(
            key: const Key('profile-bio'),
            controller: bioController,
            maxLength: 300,
            minLines: 3,
            maxLines: 5,
            decoration: const InputDecoration(
              labelText: 'About you',
              hintText: 'What would you enjoy talking about?',
            ),
            validator: (value) => UserProfile.validateBio(value ?? ''),
          ),
          const SizedBox(height: 10),
          Text('Interests', style: Theme.of(context).textTheme.titleMedium),
          const SizedBox(height: 6),
          Wrap(
            spacing: 8,
            children: availableInterests
                .map(
                  (value) => FilterChip(
                    label: Text(value),
                    selected: interests.contains(value),
                    onSelected: (selected) => setState(
                      () => selected
                          ? interests.add(value)
                          : interests.remove(value),
                    ),
                  ),
                )
                .toList(),
          ),
          if (interests.isEmpty)
            const Padding(
              padding: EdgeInsets.only(top: 6),
              child: Text(
                'Choose at least one interest.',
                style: TextStyle(color: Colors.red),
              ),
            ),
          const SizedBox(height: 12),
          SwitchListTile(
            contentPadding: EdgeInsets.zero,
            title: const Text('Show a coarse distance band'),
            subtitle: const Text('Exact location is never displayed.'),
            value: showDistanceBand,
            onChanged: (value) => setState(() => showDistanceBand = value),
          ),
          SwitchListTile(
            contentPadding: EdgeInsets.zero,
            title: const Text('Open to calls by default'),
            subtitle: const Text(
              'Calls still require a match, mutual readiness, and acceptance.',
            ),
            value: callReadyByDefault,
            onChanged: (value) => setState(() => callReadyByDefault = value),
          ),
          const SizedBox(height: 14),
          FilledButton(
            key: const Key('save-profile'),
            onPressed: _save,
            child: const Padding(
              padding: EdgeInsets.symmetric(vertical: 14),
              child: Text('Save profile'),
            ),
          ),
        ],
      ),
    ),
  );

  void _save() {
    if (!(formKey.currentState?.validate() ?? false) || interests.isEmpty) {
      return;
    }
    widget.onSaved(
      UserProfile(
        displayName: nameController.text.trim(),
        age: int.parse(ageController.text.trim()),
        intent: intent,
        bio: bioController.text.trim(),
        interests: interests.toList()..sort(),
        showDistanceBand: showDistanceBand,
        callReadyByDefault: callReadyByDefault,
      ),
    );
  }
}

class SafetySheet extends StatelessWidget {
  const SafetySheet({super.key});
  @override
  Widget build(BuildContext context) => SafeArea(
    child: SingleChildScrollView(
      padding: const EdgeInsets.fromLTRB(24, 4, 24, 24),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            'Safety center',
            style: Theme.of(context).textTheme.headlineSmall
                ?.copyWith(fontWeight: FontWeight.w800),
          ),
          const SizedBox(height: 12),
          const ListTile(
            contentPadding: EdgeInsets.zero,
            leading: Icon(Icons.block),
            title: Text('Block and report'),
            subtitle: Text(
              'Available from the prototype conversation. More safety entry points are planned.',
            ),
          ),
          const ListTile(
            contentPadding: EdgeInsets.zero,
            leading: Icon(Icons.videocam_outlined),
            title: Text('Calls require mutual readiness'),
            subtitle: Text(
              'A match can always decline. Calls are not recorded.',
            ),
          ),
          const ListTile(
            contentPadding: EdgeInsets.zero,
            leading: Icon(Icons.location_off_outlined),
            title: Text('Location stays coarse'),
            subtitle: Text(
              'Profiles show distance bands, never exact coordinates.',
            ),
          ),
          const SizedBox(height: 8),
          FilledButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('Done'),
          ),
        ],
      ),
    ),
  );
}
